using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WS_HyJ.Models.Responses;

namespace WS_HyJ.Models.Internal
{
    /// <summary>
    /// Entidad de marcas
    /// </summary>
    public class BrandEntity
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public string Nombre { get; set; }
    }
}
