using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static WS_HyJ.Models.Enum.Enums;

namespace WS_HyJ.Models.Internal
{
    /// <summary>
    /// Kardex
    /// </summary>
    public class KardexEntity
    {
        public KardexEntity()
        {
            InternalId = ObjectId.GenerateNewId(DateTime.Now);
            Id = Guid.NewGuid().ToString();
            UpdatedOn = DateTime.Now;
            CreatedOn = DateTime.Now;
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        [BsonRequired]
        // external Id
        public string Id { get; set; }

        [BsonRequired]
        public string IdProducto { get; set; }
        
        public short? MinimumAmount { get; set; }
        
        public short? CurrentAmount { get; set; } = null;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        // attribute to gain control on datetime serialization
        public DateTime UpdatedOn { get; set; }

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        // attribute to gain control on datetime serialization
        public DateTime CreatedOn { get; set; }
    }
}
