using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WS_HyJ.Models.Enum;
using WS_HyJ.Models.Requests;
using static WS_HyJ.Models.Enum.Enums;

namespace WS_HyJ.Models.Internal
{
    public class ProductEntity
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id
        [BsonRequired]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [BsonRepresentation(BsonType.Int64)]
        public int Numero { get; set; }

        /// <summary>
        /// Correlativo (P-0001)
        /// </summary>
        public string Codigo { get; set; }

        public string Nombre { get; set; }

        [BsonRepresentation(BsonType.Decimal128)]
        public decimal PrecioUnitario { get; set; }

        public ECurrencyType Moneda { get; set; }

        public EUnitOfMeasurement UM { get; set; }

        [BsonRepresentation(BsonType.Decimal128)]
        public decimal? Peso { get; set; }

        public string Tipo { get; set; }

        public string Descripcion { get; set; } = null;

        public string IdProveedor { get; set; }
        
        public BrandEntity Marca { get; set; }

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        // attribute to gain control on datetime serialization
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        // attribute to gain control on datetime serialization
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }
}
