using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WS_HyJ.Models.Internal
{
    public class ProviderEntity
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [BsonRequired]
        public string RUC { get; set; }

        [BsonRequired]
        public string RazonSocial { get; set; }

        public string Direccion { get; set; }
        
        public string Telefono { get; set; }

        public string Contacto { get; set; }

        public string Celular { get; set; }

        public string Email { get; set; }
        
        public string Descripcion { get; set; } = string.Empty;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        // attribute to gain control on datetime serialization
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        // attribute to gain control on datetime serialization
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }
}
